logging:
  config: 'classpath:log4j2.yml'
  level:
    org.sonso: debug

server:
  port: 7000

spring:
  application:
    name: hackathon-spring-2025-api
  datasource:
    username: hack
    password: hack
    #    url: jdbc:postgresql://hack_db:5432/hack  # docker-compose
    url: jdbc:postgresql://localhost:7100/hack   # idea
    driver-class-name: org.postgresql.Driver

