#logging:
#  level:
#    org.sonso: debug

server:
  port: 7000

spring:
  application:
    name: hackathon-spring-2025-api
  datasource:
    username: hack
    password: hack
    url: jdbc:postgresql://hack_db:5432/hack  # docker-compose
#    url: jdbc:postgresql://localhost:7100/hack   # idea
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: hack_redis     # docker-compose
      port: 6379
#      host: localhost     # idea
#      port: 6300

app:
  admin:
    login: admin
    password: 123123123
