CREATE TABLE IF NOT EXISTS "stats"(
    "id" int NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY ,
    "person_name" varchar(1) NOT NULL UNIQUE ,
    "reaction_time" decimal,
    "acceleration" decimal,
    "max_speed" decimal,
    "lsf" decimal,
    PRIMARY KEY ("id")
)